-- MySQL Script generated by MySQL Workbench
-- Sat Sep 18 19:24:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_cristofarma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_cristofarma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_cristofarma` DEFAULT CHARACTER SET utf8 ;
USE `projeto_cristofarma` ;

-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cpf_cnpj` VARCHAR(45) NOT NULL,
  `tipo_pessoa` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefone_fixo` VARCHAR(45) NULL,
  `telefone_celular` VARCHAR(45) NULL,
  `matricula` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `funcao` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NULL,
  `preco_custo` VARCHAR(45) NULL,
  `preco_venda` VARCHAR(45) NULL,
  `codigo_barras` VARCHAR(45) NULL,
  `produto_fornecedor` VARCHAR(45) NULL,
  `pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_produto_pessoa1_idx` (`pessoa_id_pessoa` ASC) ,
  CONSTRAINT `fk_produto_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `projeto_cristofarma`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`estoque` (
  `produto_id_produto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`produto_id_produto`),
  CONSTRAINT `fk_estoque_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `projeto_cristofarma`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `valor_venda_sem_desconto` VARCHAR(45) NULL,
  `desconto` VARCHAR(45) NULL,
  `valor_venda_com_desconto` VARCHAR(45) NULL,
  `tipo_pagamento` ENUM('a vista', 'debito', 'credito') NULL,
  `data_venda` VARCHAR(45) NULL,
  `vendedor` VARCHAR(45) NULL,
  `cliente` VARCHAR(45) NULL,
  `total_item_venda` VARCHAR(45) NULL,
  `pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_pessoa1_idx` (`pessoa_id_pessoa` ASC) ,
  CONSTRAINT `fk_venda_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `projeto_cristofarma`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`cupom_fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`cupom_fiscal` (
  `id_cupom` INT NOT NULL AUTO_INCREMENT,
  `venda_id_venda` INT NOT NULL,
  PRIMARY KEY (`id_cupom`),
  INDEX `fk_cupom_venda1_idx` (`venda_id_venda` ASC) ,
  CONSTRAINT `fk_cupom_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `projeto_cristofarma`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`produto_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`produto_venda` (
  `produto_id_produto` INT NOT NULL,
  `venda_id_venda` INT NOT NULL,
  PRIMARY KEY (`produto_id_produto`, `venda_id_venda`),
  INDEX `fk_produto_has_venda_venda1_idx` (`venda_id_venda` ASC) ,
  INDEX `fk_produto_has_venda_produto1_idx` (`produto_id_produto` ASC) ,
  CONSTRAINT `fk_produto_has_venda_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `projeto_cristofarma`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_venda_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `projeto_cristofarma`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`item_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`item_compra` (
  `id_item_compra` INT NOT NULL AUTO_INCREMENT,
  `produto_id_produto` INT NOT NULL,
  PRIMARY KEY (`id_item_compra`),
  INDEX `fk_item_compra_produto1_idx` (`produto_id_produto` ASC) ,
  CONSTRAINT `fk_item_compra_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `projeto_cristofarma`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
