produto-- MySQL Script generated by MySQL Workbench
-- Fri Jun 18 09:11:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_cristofarma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_cristofarma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_cristofarma` DEFAULT CHARACTER SET utf8 ;
USE `projeto_cristofarma` ;

-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`pessoa` (
  `id_pessoa` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefone_fixo` VARCHAR(15) NULL,
  `telefone_celular` VARCHAR(15) NULL,
  `endereco` VARCHAR(100) NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`endereco` (
  `id_endereco` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NOT NULL,
  `quadra` VARCHAR(11) NULL,
  `lote` VARCHAR(11) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(11) NULL,
  `cep` VARCHAR(11) NULL,
  `pessoa_id_pessoa` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_endereco_pessoa1_idx` (`pessoa_id_pessoa` ASC) ,
  CONSTRAINT `fk_endereco_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `projeto_cristofarma`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`pessoa_juridica` (
  `cnpj` VARCHAR(20) NOT NULL,
  `pessoa_id_pessoa` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`cnpj`),
  INDEX `fk_pessoa_juridica_pessoa1_idx` (`pessoa_id_pessoa` ASC) ,
  CONSTRAINT `fk_pessoa_juridica_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `projeto_cristofarma`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`fornecedor` (
  `pessoa_juridica_cnpj` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`pessoa_juridica_cnpj`),
  INDEX `fk_fornecedor_pessoa_juridica1_idx` (`pessoa_juridica_cnpj` ASC) ,
  CONSTRAINT `fk_fornecedor_pessoa_juridica1`
    FOREIGN KEY (`pessoa_juridica_cnpj`)
    REFERENCES `projeto_cristofarma`.`pessoa_juridica` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`pessoa_fisica` (
  `cpf` VARCHAR(11) NOT NULL,
  `pessoa_id_pessoa` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_pessoa_fisica_pessoa1_idx` (`pessoa_id_pessoa` ASC) ,
  CONSTRAINT `fk_pessoa_fisica_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `projeto_cristofarma`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`funcionario` (
  `matricula` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(20) NULL,
  `pessoa_fisica_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_funcionario_pessoa_fisica1_idx` (`pessoa_fisica_cpf` ASC) ,
  CONSTRAINT `fk_funcionario_pessoa_fisica1`
    FOREIGN KEY (`pessoa_fisica_cpf`)
    REFERENCES `projeto_cristofarma`.`pessoa_fisica` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`venda` (
  `id_venda` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor_venda` VARCHAR(11) NOT NULL,
  `desconto` VARCHAR(11) NULL,
  `valor_total` VARCHAR(11) NULL,
  `tipo_pagamento` ENUM('1', '2', '3') NOT NULL,
  `data_venda` VARCHAR(20) NOT NULL,
  `total_itens_venda` INT(11) NULL,
  `pessoa_id_pessoa` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_pessoa1_idx` (`pessoa_id_pessoa` ASC) ,
  CONSTRAINT `fk_venda_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `projeto_cristofarma`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`produto` (
  `id_produto` INT(11) NOT NULL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `fornecedor` VARCHAR(45) NOT NULL,
  `preco_custo` VARCHAR(45) NOT NULL,
  `preco_venda` VARCHAR(45) NULL,
  `codigo_barras` VARCHAR(45) NULL,
  `fornecedor_pessoa_juridica_cnpj` VARCHAR(20) NOT NULL,
  INDEX `fk_produto_fornecedor1_idx` (`fornecedor_pessoa_juridica_cnpj` ASC) ,
  PRIMARY KEY (`id_produto`),
  CONSTRAINT `fk_produto_fornecedor1`
    FOREIGN KEY (`fornecedor_pessoa_juridica_cnpj`)
    REFERENCES `projeto_cristofarma`.`fornecedor` (`pessoa_juridica_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`estoque` (
  `quantidade_estoque` VARCHAR(45) NULL,
  `produto_id_produto` INT NOT NULL,
  INDEX `fk_estoque_produto_idx` (`produto_id_produto` ASC) ,
  CONSTRAINT `fk_estoque_produto`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `mydb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`item_venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`item_venda_produto` (
  `data_venda_produto` VARCHAR(20) NOT NULL,
  `venda_id_venda` INT(11) UNSIGNED NOT NULL,
  `produto_id_produto` INT(11) NOT NULL,
  INDEX `fk_produto_has_venda_venda1_idx` (`venda_id_venda` ASC) ,
  INDEX `fk_item_venda_produto_produto1_idx` (`produto_id_produto` ASC) ,
  PRIMARY KEY (`venda_id_venda`, `produto_id_produto`),
  CONSTRAINT `fk_produto_has_venda_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `projeto_cristofarma`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_venda_produto_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `projeto_cristofarma`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`cupom_fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`cupom_fiscal` (
  `venda_id_venda` INT(11) UNSIGNED NOT NULL,
  INDEX `fk_cupom_fiscal_venda1_idx` (`venda_id_venda` ASC) ,
  PRIMARY KEY (`venda_id_venda`),
  CONSTRAINT `fk_cupom_fiscal_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `projeto_cristofarma`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
