-- MySQL Script generated by MySQL Workbench
-- Sat Aug 28 21:35:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_cristofarma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_cristofarma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_cristofarma` DEFAULT CHARACTER SET utf8 ;
USE `projeto_cristofarma` ;

-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefone_fixo` VARCHAR(45) NULL,
  `telefone_celular` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NULL,
  `quadra` VARCHAR(45) NULL,
  `lote` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `fk_endereco_pessoa1_idx` (`pessoa_id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `projeto_cristofarma`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`pessoa_fisica` (
  `cpf` INT NOT NULL,
  `rg` VARCHAR(45) NULL,
  `pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`cpf`, `pessoa_id_pessoa`),
  INDEX `fk_pessoa_fisica_pessoa1_idx` (`pessoa_id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_fisica_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `projeto_cristofarma`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`pessoa_juridica` (
  `cnpj` INT NOT NULL,
  `pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`cnpj`, `pessoa_id_pessoa`),
  INDEX `fk_pessoa_juridica_pessoa1_idx` (`pessoa_id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_juridica_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `projeto_cristofarma`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`funcionario` (
  `matricula` INT NOT NULL,
  `senha` VARCHAR(45) NULL,
  `funcao` VARCHAR(45) NULL,
  `pessoa_fisica_cpf` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_funcionario_pessoa_fisica1_idx` (`pessoa_fisica_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_pessoa_fisica1`
    FOREIGN KEY (`pessoa_fisica_cpf`)
    REFERENCES `projeto_cristofarma`.`pessoa_fisica` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`fornecedor` (
  `pessoa_juridica_cnpj` INT NOT NULL,
  INDEX `fk_fornecedor_pessoa_juridica1_idx` (`pessoa_juridica_cnpj` ASC) VISIBLE,
  PRIMARY KEY (`pessoa_juridica_cnpj`),
  CONSTRAINT `fk_fornecedor_pessoa_juridica1`
    FOREIGN KEY (`pessoa_juridica_cnpj`)
    REFERENCES `projeto_cristofarma`.`pessoa_juridica` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NULL,
  `preco_custo` VARCHAR(45) NULL,
  `preco_venda` VARCHAR(45) NULL,
  `codigo_barras` VARCHAR(45) NULL,
  `fornecedor_pessoa_juridica_cnpj` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_produto_fornecedor1_idx` (`fornecedor_pessoa_juridica_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_produto_fornecedor1`
    FOREIGN KEY (`fornecedor_pessoa_juridica_cnpj`)
    REFERENCES `projeto_cristofarma`.`fornecedor` (`pessoa_juridica_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`estoque` (
  `produto_id_produto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  INDEX `fk_estoque_produto1_idx` (`produto_id_produto` ASC) VISIBLE,
  PRIMARY KEY (`produto_id_produto`),
  CONSTRAINT `fk_estoque_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `projeto_cristofarma`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `valor_venda_sem_desconto` VARCHAR(45) NULL,
  `desconto` VARCHAR(45) NULL,
  `valor_venda_com_desconto` VARCHAR(45) NULL,
  `vendacol` VARCHAR(45) NULL,
  `tipo_pagamento` VARCHAR(45) NULL,
  `data_venda` VARCHAR(45) NULL,
  `vendedor` VARCHAR(45) NULL,
  `cliente` VARCHAR(45) NULL,
  `cliente_pessoa_fisica_cpf` INT NOT NULL,
  `cliente_pessoa_juridica_cnpj` INT NOT NULL,
  `pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_pessoa1_idx` (`pessoa_id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_venda_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `projeto_cristofarma`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`venda_produto` (
  `venda_id_venda` INT NOT NULL,
  `produto_id_produto` INT NOT NULL,
  PRIMARY KEY (`venda_id_venda`, `produto_id_produto`),
  INDEX `fk_venda_has_produto_produto1_idx` (`produto_id_produto` ASC) VISIBLE,
  INDEX `fk_venda_has_produto_venda1_idx` (`venda_id_venda` ASC) VISIBLE,
  CONSTRAINT `fk_venda_has_produto_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `projeto_cristofarma`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_produto_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `projeto_cristofarma`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_cristofarma`.`cupom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_cristofarma`.`cupom` (
  `id_cupom` INT NOT NULL,
  `venda_id_venda` INT NOT NULL,
  PRIMARY KEY (`id_cupom`),
  INDEX `fk_cupom_venda1_idx` (`venda_id_venda` ASC) VISIBLE,
  CONSTRAINT `fk_cupom_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `projeto_cristofarma`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
